version: "3"
services:
  node-app:
    container_name: university-dev-container
    ports:
      - "5000:5000"
    env_file:
      - ./config/config.env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
